### ISSUE TITLE
Element6 Clean up

### ISSUE THREAD

**Issue by wengerm50** [FHWA/RDE-Visualization-Website#17]
Need to remove the inline css and add it to the element6 css file.
Go over the javascript and fix indenting.
Go over the javascript and remove junk comments.

**Comment by clayheaton** [comment]
There's also custom CSS for the `h3` element that is being pulled in from `custom.css` and affecting the styling of the "Methodology" and "Download Instructions" headers. That needs to be cleaned up so that the elements that need the custom `h3` class are designated such in the HTML for the visualization, leaving the vanilla `h3` as defined in `styleguide.css`.
